/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package klinikuntan;

/**
 *
 * @author User
 */
public class Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Dokter
     */
    public Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        dokterTabbedPane = new javax.swing.JTabbedPane();
        pemeriksaanTabbedPaneByDokter = new javax.swing.JTabbedPane();
        panelDiagnosaPemeriksaan = new javax.swing.JPanel();
        labelKodePemeriksaan3 = new javax.swing.JLabel();
        labelDiagnosa2 = new javax.swing.JLabel();
        textKdPemeriksaanDokter = new javax.swing.JTextField();
        buttonDiagnosaPemeriksaan = new javax.swing.JButton();
        scrollPaneDiagnosaPemeriksaan = new javax.swing.JScrollPane();
        textAreaDiagnosaPemeriksaan = new javax.swing.JTextArea();
        ResepTabbedPane = new javax.swing.JTabbedPane();
        panelTambahObatResep = new javax.swing.JPanel();
        textDosisObat = new javax.swing.JTextField();
        labelObat3 = new javax.swing.JLabel();
        buttonTambahResep = new javax.swing.JButton();
        labelNamaObat3 = new javax.swing.JLabel();
        textNamaObatResep = new javax.swing.JTextField();
        labelStok3 = new javax.swing.JLabel();
        textJumlahObatResep = new javax.swing.JTextField();
        labelObat4 = new javax.swing.JLabel();
        scrollPaneDeskripsiResep = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        panelResepObat = new javax.swing.JPanel();
        scrollPaneResep = new javax.swing.JScrollPane();
        tableResepObat = new javax.swing.JTable();
        buttonCetakResep = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Dokter");

        dokterTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        dokterTabbedPane.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        labelKodePemeriksaan3.setText("Kode Pemeriksaan");
        labelKodePemeriksaan3.setPreferredSize(new java.awt.Dimension(90, 25));

        labelDiagnosa2.setText("Diagnosa");
        labelDiagnosa2.setPreferredSize(new java.awt.Dimension(90, 25));

        textKdPemeriksaanDokter.setPreferredSize(new java.awt.Dimension(300, 25));

        buttonDiagnosaPemeriksaan.setText("Tambah");
        buttonDiagnosaPemeriksaan.setMaximumSize(new java.awt.Dimension(80, 25));
        buttonDiagnosaPemeriksaan.setMinimumSize(new java.awt.Dimension(80, 25));
        buttonDiagnosaPemeriksaan.setPreferredSize(new java.awt.Dimension(80, 25));
        buttonDiagnosaPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDiagnosaPemeriksaanActionPerformed(evt);
            }
        });

        textAreaDiagnosaPemeriksaan.setColumns(20);
        textAreaDiagnosaPemeriksaan.setRows(5);
        scrollPaneDiagnosaPemeriksaan.setViewportView(textAreaDiagnosaPemeriksaan);

        javax.swing.GroupLayout panelDiagnosaPemeriksaanLayout = new javax.swing.GroupLayout(panelDiagnosaPemeriksaan);
        panelDiagnosaPemeriksaan.setLayout(panelDiagnosaPemeriksaanLayout);
        panelDiagnosaPemeriksaanLayout.setHorizontalGroup(
            panelDiagnosaPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiagnosaPemeriksaanLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelDiagnosaPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelKodePemeriksaan3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiagnosa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(panelDiagnosaPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textKdPemeriksaanDokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneDiagnosaPemeriksaan))
                .addGap(167, 167, 167))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDiagnosaPemeriksaanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonDiagnosaPemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );
        panelDiagnosaPemeriksaanLayout.setVerticalGroup(
            panelDiagnosaPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDiagnosaPemeriksaanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelDiagnosaPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelKodePemeriksaan3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textKdPemeriksaanDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelDiagnosaPemeriksaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneDiagnosaPemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiagnosa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(buttonDiagnosaPemeriksaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        pemeriksaanTabbedPaneByDokter.addTab("Diagnosa Pasien", panelDiagnosaPemeriksaan);

        dokterTabbedPane.addTab("Pemeriksaan", pemeriksaanTabbedPaneByDokter);

        textDosisObat.setPreferredSize(new java.awt.Dimension(300, 25));

        labelObat3.setText("Dosis");
        labelObat3.setPreferredSize(new java.awt.Dimension(90, 25));

        buttonTambahResep.setText("Perbarui");
        buttonTambahResep.setPreferredSize(new java.awt.Dimension(72, 25));

        labelNamaObat3.setText("Nama Obat");
        labelNamaObat3.setPreferredSize(new java.awt.Dimension(90, 25));

        textNamaObatResep.setPreferredSize(new java.awt.Dimension(300, 25));

        labelStok3.setText("Jumlah");
        labelStok3.setPreferredSize(new java.awt.Dimension(90, 25));

        textJumlahObatResep.setPreferredSize(new java.awt.Dimension(300, 25));

        labelObat4.setText("Deskripsi");
        labelObat4.setPreferredSize(new java.awt.Dimension(90, 25));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setPreferredSize(new java.awt.Dimension(300, 84));
        scrollPaneDeskripsiResep.setViewportView(jTextArea2);

        javax.swing.GroupLayout panelTambahObatResepLayout = new javax.swing.GroupLayout(panelTambahObatResep);
        panelTambahObatResep.setLayout(panelTambahObatResepLayout);
        panelTambahObatResepLayout.setHorizontalGroup(
            panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTambahObatResepLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonTambahResep, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(panelTambahObatResepLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNamaObat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStok3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textDosisObat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textJumlahObatResep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textNamaObatResep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollPaneDeskripsiResep))
                .addGap(167, 167, 167))
        );
        panelTambahObatResepLayout.setVerticalGroup(
            panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTambahObatResepLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textNamaObatResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaObat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textJumlahObatResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStok3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textDosisObat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTambahObatResepLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneDeskripsiResep, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelObat4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(278, 278, 278)
                .addComponent(buttonTambahResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        ResepTabbedPane.addTab("Buat Resep", panelTambahObatResep);

        scrollPaneResep.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        tableResepObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "NO", "Nama Obat", "Jumlah", "Dosis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPaneResep.setViewportView(tableResepObat);
        if (tableResepObat.getColumnModel().getColumnCount() > 0) {
            tableResepObat.getColumnModel().getColumn(0).setResizable(false);
            tableResepObat.getColumnModel().getColumn(0).setPreferredWidth(5);
            tableResepObat.getColumnModel().getColumn(1).setResizable(false);
            tableResepObat.getColumnModel().getColumn(2).setResizable(false);
            tableResepObat.getColumnModel().getColumn(3).setResizable(false);
        }

        buttonCetakResep.setText("Cetak");
        buttonCetakResep.setPreferredSize(new java.awt.Dimension(80, 25));

        javax.swing.GroupLayout panelResepObatLayout = new javax.swing.GroupLayout(panelResepObat);
        panelResepObat.setLayout(panelResepObatLayout);
        panelResepObatLayout.setHorizontalGroup(
            panelResepObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResepObatLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelResepObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonCetakResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPaneResep, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE))
                .addGap(57, 57, 57))
        );
        panelResepObatLayout.setVerticalGroup(
            panelResepObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResepObatLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(scrollPaneResep, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(buttonCetakResep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        ResepTabbedPane.addTab("Cetak Resep", panelResepObat);

        dokterTabbedPane.addTab("Resep", ResepTabbedPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(dokterTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(dokterTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonDiagnosaPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDiagnosaPemeriksaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonDiagnosaPemeriksaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dokter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dokter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ResepTabbedPane;
    private javax.swing.JButton buttonCetakResep;
    private javax.swing.JButton buttonDiagnosaPemeriksaan;
    private javax.swing.JButton buttonTambahResep;
    private javax.swing.JTabbedPane dokterTabbedPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel labelDiagnosa2;
    private javax.swing.JLabel labelKodePemeriksaan3;
    private javax.swing.JLabel labelNamaObat3;
    private javax.swing.JLabel labelObat3;
    private javax.swing.JLabel labelObat4;
    private javax.swing.JLabel labelStok3;
    private javax.swing.JPanel panelDiagnosaPemeriksaan;
    private javax.swing.JPanel panelResepObat;
    private javax.swing.JPanel panelTambahObatResep;
    private javax.swing.JTabbedPane pemeriksaanTabbedPaneByDokter;
    private javax.swing.JScrollPane scrollPaneDeskripsiResep;
    private javax.swing.JScrollPane scrollPaneDiagnosaPemeriksaan;
    private javax.swing.JScrollPane scrollPaneResep;
    private javax.swing.JTable tableResepObat;
    private javax.swing.JTextArea textAreaDiagnosaPemeriksaan;
    private javax.swing.JTextField textDosisObat;
    private javax.swing.JTextField textJumlahObatResep;
    private javax.swing.JTextField textKdPemeriksaanDokter;
    private javax.swing.JTextField textNamaObatResep;
    // End of variables declaration//GEN-END:variables
}
